# Generated by Django 4.1.1 on 2022-09-24 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregatetype", models.CharField(max_length=255)),
                ("aggregateid", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("payload", models.BinaryField()),
            ],
        ),
    ]
