# Generated by Django 4.1.1 on 2022-09-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_add_outbox_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outbox",
            old_name="type",
            new_name="event_type",
        ),
    ]
