# Generated by Django 4.1.1 on 2022-09-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_modify_outbox_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outbox",
            old_name="event_type",
            new_name="type",
        ),
    ]
